import { StyleSheet } from "react-native";

export const C = {
  bg: "#020A14",
  panel: "rgba(3,13,27,0.86)",
  card: "#071426",
  border: "#33445C",
  text: "#F5F7FB",
  muted: "#AEB7C8",
  orange: "#FF6800",
  purple: "#8B4DFF",
  cyan: "#22D3EE",
  cyanSoft: "rgba(34,211,238,0.14)",
  blue: "#7288AA",
  green: "#23C96B"
};

export const styles = StyleSheet.create({
  background: { flex: 1, backgroundColor: C.bg },
  backgroundImage: { transform: [{ translateY: 168 }, { scale: 1.14 }] },
  backgroundOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(2,10,20,0.44)" },
  safe: { flex: 1, backgroundColor: "transparent" },
  scroll: { flexGrow: 1, alignItems: "center", backgroundColor: "transparent" },
  frame: { width: "100%", maxWidth: 540, minHeight: "100%", backgroundColor: "transparent" },
  panel: { marginHorizontal: 4, paddingHorizontal: 30, paddingTop: 14, paddingBottom: 18, borderWidth: 0, borderRadius: 10, backgroundColor: "rgba(3,13,27,0.92)" },
  setupIntro: { marginBottom: 14 },
  setupTitle: { fontSize: 30, lineHeight: 36, fontWeight: "900", letterSpacing: -0.4 },
  setupSubtitle: { marginTop: 4, color: C.muted, fontSize: 15, lineHeight: 21, fontWeight: "500" },
  sectionTitle: { color: C.orange, fontSize: 18, lineHeight: 23, fontWeight: "800", marginBottom: 8 },
  variant: { minHeight: 82, borderRadius: 13, borderWidth: 1, borderColor: C.border, backgroundColor: "rgba(5,15,29,0.86)", marginBottom: 8, paddingHorizontal: 12, paddingVertical: 6, flexDirection: "row", alignItems: "center", position: "relative", overflow: "visible" },
  selected: { borderColor: C.orange, borderWidth: 1.7 },
  fogSelected: { borderColor: "#B8C2CF", backgroundColor: "rgba(5,15,29,0.86)", shadowColor: "#B8C2CF", shadowOpacity: 0.18, shadowRadius: 8, shadowOffset: { width: 0, height: 0 }, elevation: 5 },
  sonarSelected: { borderColor: C.cyan, backgroundColor: "rgba(5,15,29,0.86)", shadowColor: C.cyan, shadowOpacity: 0.46, shadowRadius: 12, shadowOffset: { width: 0, height: 0 }, elevation: 8 },
  fogCardGlow: { display: "none" },
  sonarCardGlow: { display: "none" },
  pressed: { opacity: 0.78 },
  visual: { width: 74, alignItems: "center", justifyContent: "center", marginRight: 12 },
  visualSonarActive: { width: 78 },
  graphic: { width: 56, height: 56, borderRadius: 28, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  fogGraphic: { backgroundColor: "rgba(48,56,70,0.72)", borderWidth: 1, borderColor: "rgba(205,214,226,0.32)", shadowColor: "#AEB7C8", shadowOpacity: 0.22, shadowRadius: 7 },
  fogGraphicActive: { width: 62, height: 62, borderRadius: 31, borderWidth: 1.3, borderColor: "rgba(220,227,236,0.68)", shadowOpacity: 0.36, shadowRadius: 9, elevation: 6 },
  graphicRing: { position: "absolute", borderWidth: 1, borderRadius: 50, borderColor: "rgba(224,231,239,0.3)" },
  graphicRingOuter: { width: 48, height: 48 },
  graphicRingMiddle: { width: 32, height: 32 },
  graphicRingInner: { width: 17, height: 17 },
  graphicLineHorizontal: { position: "absolute", width: 42, height: 1, backgroundColor: "rgba(224,231,239,0.24)" },
  graphicLineVertical: { position: "absolute", width: 1, height: 42, backgroundColor: "rgba(224,231,239,0.24)" },
  graphicDot: { width: 11, height: 11, borderRadius: 6, backgroundColor: C.orange, borderWidth: 1.5, borderColor: "#FFFFFF", zIndex: 3 },
  fogHalo: { position: "absolute", width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(168,178,190,0.16)" },
  fogHaloActive: { width: 50, height: 50, borderRadius: 25, backgroundColor: "rgba(205,214,226,0.18)" },
  fogMistBandOne: { position: "absolute", width: 52, height: 10, borderRadius: 6, top: 17, backgroundColor: "rgba(225,231,238,0.07)", transform: [{ rotate: "-8deg" }] },
  fogMistBandTwo: { position: "absolute", width: 46, height: 9, borderRadius: 5, bottom: 16, backgroundColor: "rgba(225,231,238,0.06)", transform: [{ rotate: "7deg" }] },
  sonarGraphic: { width: 60, height: 60, borderRadius: 30, backgroundColor: "rgba(4,19,28,0.92)", borderWidth: 1.6, borderColor: "rgba(34,211,238,0.72)", shadowColor: C.cyan, shadowOpacity: 0.34, shadowRadius: 8, elevation: 6 },
  sonarGraphicActive: { width: 64, height: 64, borderRadius: 32, borderWidth: 1.8, borderColor: C.cyan, shadowColor: C.cyan, shadowOpacity: 0.58, shadowRadius: 11, shadowOffset: { width: 0, height: 0 }, elevation: 8 },
  sonarRingOuter: { width: 48, height: 48, borderColor: "rgba(34,211,238,0.58)" },
  sonarRingMiddle: { width: 34, height: 34, borderColor: "rgba(34,211,238,0.62)" },
  sonarRingInner: { width: 17, height: 17, borderColor: "rgba(34,211,238,0.72)" },
  sonarAxisHorizontal: { position: "absolute", width: 52, height: 1, backgroundColor: "rgba(34,211,238,0.34)" },
  sonarAxisVertical: { position: "absolute", width: 1, height: 52, backgroundColor: "rgba(34,211,238,0.34)" },
  sonarPulse: { position: "absolute", width: 52, height: 52, borderRadius: 26, borderWidth: 1.5, borderColor: "rgba(34,211,238,0.72)" },
  sonarSweep: { position: "absolute", width: 60, height: 60, alignItems: "center", justifyContent: "flex-start" },
  sonarBeam: { width: 2, height: 29, marginTop: 2, backgroundColor: C.cyan, opacity: 0.9 },
  sonarBlip: { position: "absolute", width: 7, height: 7, borderRadius: 4, top: 14, right: 13, backgroundColor: C.cyan, shadowColor: C.cyan, shadowOpacity: 0.9, shadowRadius: 7, elevation: 7 },
  sonarCoreOuter: { width: 16, height: 16, borderRadius: 8, backgroundColor: "#E8FDFF", alignItems: "center", justifyContent: "center", zIndex: 3 },
  sonarCoreInner: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.cyan },
  variantCopy: { flex: 1, minWidth: 0, paddingRight: 34 },
  variantTitle: { color: C.text, fontSize: 19, lineHeight: 23, fontWeight: "800", marginBottom: 1 },
  fogText: { color: "#E3E8EF", textShadowColor: "rgba(205,214,226,0.24)", textShadowRadius: 4 },
  sonarText: { color: C.cyan, textShadowColor: "rgba(34,211,238,0.4)", textShadowRadius: 5 },
  variantDescription: { color: C.muted, fontSize: 14, lineHeight: 18 },
  variantMark: { position: "absolute", top: 20, right: 12 },
  mark: { width: 30, height: 30, borderRadius: 15, borderWidth: 1.5, borderColor: "#6E819F", alignItems: "center", justifyContent: "center", alignSelf: "flex-start" },
  markSmall: { width: 22, height: 22, borderRadius: 11 },
  markOn: { backgroundColor: C.orange, borderColor: C.orange },
  markOnSonar: { backgroundColor: C.cyan, borderColor: C.cyan, shadowColor: C.cyan, shadowOpacity: 0.65, shadowRadius: 8 },
  check: { color: "#111315", fontSize: 16, fontWeight: "900" },
  checkSonar: { color: "#02202A" },
  subhead: { color: C.text, fontSize: 17, lineHeight: 21, fontWeight: "800", marginTop: 2, marginBottom: 6 },
  row: { flexDirection: "row", gap: 8, marginBottom: 8 },
  difficultyRow: { gap: 6, marginBottom: 8 },
  player: { flex: 1, minHeight: 52, borderRadius: 11, borderWidth: 1, borderColor: C.border, backgroundColor: C.card, paddingLeft: 11, paddingRight: 34, flexDirection: "row", alignItems: "center", position: "relative" },
  playerIcon: { fontSize: 15, marginRight: 6 },
  playerText: { flex: 1, minWidth: 0, color: C.text, fontSize: 15, lineHeight: 20, fontWeight: "600" },
  playerMark: { position: "absolute", top: 8, right: 7 },
  inlineContactButton: { flex: 1, minHeight: 52, borderRadius: 11, borderWidth: 1, borderColor: C.orange, backgroundColor: C.card, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", justifyContent: "center" },
  inlineContactIcon: { color: C.orange, fontSize: 22, lineHeight: 24, marginRight: 6, fontWeight: "800" },
  inlineContactText: { flexShrink: 1, color: C.text, fontSize: 15, lineHeight: 19, fontWeight: "800", textAlign: "center" },
  difficulty: { minHeight: 46, borderRadius: 11, borderWidth: 1, borderColor: C.border, backgroundColor: C.card, paddingHorizontal: 11, flexDirection: "row", alignItems: "center" },
  diffStarsBox: { width: 54, marginRight: 10 },
  stars: { fontSize: 18, lineHeight: 22, letterSpacing: 0.2 },
  diffCopy: { flex: 1, minWidth: 0 },
  diffTitle: { color: C.text, fontSize: 17, lineHeight: 20, fontWeight: "800" },
  diffSubtitle: { color: C.muted, fontSize: 14, lineHeight: 17, marginTop: 0 },
  diffMark: { marginLeft: 8 },
  difficultyInfo: { borderWidth: 1, borderColor: "rgba(255,104,0,0.58)", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 8, marginTop: 0, marginBottom: 10, backgroundColor: "rgba(17,29,45,0.92)" },
  difficultyInfoTitle: { color: C.text, fontSize: 17, lineHeight: 21, fontWeight: "900", marginBottom: 1 },
  difficultyInfoText: { color: C.muted, fontSize: 15, lineHeight: 19, marginBottom: 4 },
  infoRow: { minHeight: 22, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  infoLabel: { color: C.muted, fontSize: 14, lineHeight: 18, fontWeight: "700" },
  infoValue: { flexShrink: 1, color: C.text, fontSize: 14, lineHeight: 18, fontWeight: "800", textAlign: "right" },
  inviteSummary: { borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 10, marginBottom: 10, backgroundColor: C.card },
  inviteSummaryTitle: { color: C.text, fontSize: 14, fontWeight: "700", marginBottom: 8 },
  friendChip: { minHeight: 44, borderRadius: 10, backgroundColor: "rgba(20,39,61,0.95)", paddingHorizontal: 12, marginBottom: 6, flexDirection: "row", alignItems: "center" },
  friendChipText: { flex: 1, color: C.text, fontSize: 14 },
  friendRemove: { color: C.orange, fontSize: 26, lineHeight: 30, paddingHorizontal: 6 },
  button: { minHeight: 50, borderRadius: 12, backgroundColor: C.orange, alignItems: "center", justifyContent: "center", marginTop: 4, elevation: 6 },
  buttonPressed: { opacity: 0.82 },
  buttonText: { color: "#111315", fontSize: 21, lineHeight: 25, fontWeight: "900" },
  modalSafe: { flex: 1, backgroundColor: C.bg },
  modalHeader: { minHeight: 76, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: C.border },
  modalTitle: { color: C.text, fontSize: 24, fontWeight: "900" },
  modalSubtitle: { color: C.muted, fontSize: 13, marginTop: 2 },
  doneButton: { minWidth: 64, minHeight: 44, borderRadius: 12, backgroundColor: C.orange, alignItems: "center", justifyContent: "center", paddingHorizontal: 14 },
  doneButtonText: { color: "#111315", fontSize: 15, fontWeight: "900" },
  contactList: { padding: 14 },
  contactRow: { minHeight: 66, borderRadius: 12, borderWidth: 1, borderColor: C.border, paddingHorizontal: 12, marginBottom: 8, flexDirection: "row", alignItems: "center", backgroundColor: C.card },
  contactRowSelected: { borderColor: C.orange, backgroundColor: "rgba(80,38,8,0.42)" },
  contactAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#17304E", alignItems: "center", justifyContent: "center", marginRight: 12 },
  contactAvatarText: { color: C.text, fontSize: 17, fontWeight: "900" },
  contactCopy: { flex: 1, minWidth: 0 },
  contactName: { color: C.text, fontSize: 16, fontWeight: "800" },
  contactPhone: { color: C.muted, fontSize: 13, marginTop: 2 },
  emptyText: { color: C.muted, fontSize: 15, textAlign: "center", marginTop: 40 }
});
