import { StyleSheet } from "react-native";

export const COLORS = {
  background: "#020A14",
  panel: "#081524",
  card: "#0A1829",
  border: "#33445C",
  text: "#F5F7FB",
  muted: "#AEB7C8",
  orange: "#FF6800",
  blue: "#3B82F6",
  green: "#22C55E"
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  frame: { flex: 1, width: "100%", maxWidth: 540, alignSelf: "center" },
  mapStage: { flex: 1, minHeight: 520, backgroundColor: "#172437", overflow: "hidden" },
  mapBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "#19283B" },
  road: { position: "absolute", height: 5, borderRadius: 5, backgroundColor: "#67788F" },
  roadOne: { width: "130%", top: 150, left: -42, transform: [{ rotate: "-13deg" }] },
  roadTwo: { width: "120%", top: 330, left: -18, transform: [{ rotate: "10deg" }] },
  roadThree: { width: "92%", top: 255, left: 96, transform: [{ rotate: "-58deg" }] },
  block: { position: "absolute", borderRadius: 12, backgroundColor: "#27384E" },
  blockOne: { width: 104, height: 72, top: 76, left: 32 },
  blockTwo: { width: 126, height: 74, top: 214, right: 26 },
  blockThree: { width: 88, height: 112, bottom: 102, left: 44 },
  fog: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(2,10,20,0.72)" },
  sightCircle: {
    position: "absolute",
    width: 230,
    height: 230,
    borderRadius: 115,
    left: "50%",
    top: "47%",
    marginLeft: -115,
    marginTop: -115,
    backgroundColor: "rgba(59,130,246,0.12)",
    borderWidth: 1.5,
    borderColor: "rgba(147,197,253,0.42)"
  },
  sonarRingLarge: {
    position: "absolute",
    width: 270,
    height: 270,
    borderRadius: 135,
    left: "50%",
    top: "47%",
    marginLeft: -135,
    marginTop: -135,
    borderWidth: 1,
    borderColor: "rgba(255,104,0,0.22)"
  },
  sonarRingSmall: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    left: "50%",
    top: "47%",
    marginLeft: -75,
    marginTop: -75,
    borderWidth: 1,
    borderColor: "rgba(255,104,0,0.52)"
  },
  playerOuter: {
    position: "absolute",
    left: "50%",
    top: "47%",
    width: 28,
    height: 28,
    marginLeft: -14,
    marginTop: -14,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.blue,
    shadowOpacity: 0.7,
    shadowRadius: 12
  },
  playerInner: { width: 16, height: 16, borderRadius: 8, backgroundColor: COLORS.blue },
  treasurePulse: {
    position: "absolute",
    width: 38,
    height: 38,
    borderRadius: 19,
    right: 70,
    top: 180,
    backgroundColor: "rgba(255,104,0,0.18)",
    borderWidth: 1.5,
    borderColor: "rgba(255,104,0,0.8)",
    alignItems: "center",
    justifyContent: "center"
  },
  treasureDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: COLORS.orange },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 8,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between"
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(3,11,23,0.78)",
    borderWidth: 1,
    borderColor: "rgba(226,232,240,0.75)",
    alignItems: "center",
    justifyContent: "center"
  },
  iconText: { color: COLORS.orange, fontSize: 28, lineHeight: 30, fontWeight: "700" },
  titleGroup: { alignItems: "center" },
  title: { color: COLORS.text, fontSize: 18, fontWeight: "900" },
  subtitle: { color: COLORS.orange, fontSize: 12, fontWeight: "800", marginTop: 2 },
  statsRow: {
    position: "absolute",
    top: 66,
    left: 18,
    right: 18,
    flexDirection: "row",
    gap: 8
  },
  statPill: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: "rgba(3,11,23,0.82)",
    borderWidth: 1,
    borderColor: "rgba(51,68,92,0.9)",
    alignItems: "center",
    justifyContent: "center"
  },
  statValue: { color: COLORS.text, fontSize: 15, fontWeight: "900" },
  statLabel: { color: COLORS.muted, fontSize: 10, marginTop: 1 },
  recenterButton: {
    position: "absolute",
    right: 18,
    bottom: 154,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "rgba(3,11,23,0.88)",
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center"
  },
  recenterText: { color: COLORS.text, fontSize: 21 },
  bottomPanel: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    borderRadius: 18,
    backgroundColor: "rgba(8,21,36,0.96)",
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14
  },
  panelTop: { flexDirection: "row", alignItems: "center" },
  signalDot: { width: 11, height: 11, borderRadius: 6, backgroundColor: COLORS.green, marginRight: 9 },
  signalTextWrap: { flex: 1 },
  signalTitle: { color: COLORS.text, fontSize: 16, fontWeight: "900" },
  signalHelp: { color: COLORS.muted, fontSize: 12, marginTop: 2 },
  modeBadge: {
    minWidth: 74,
    height: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    backgroundColor: "rgba(255,104,0,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,104,0,0.5)",
    alignItems: "center",
    justifyContent: "center"
  },
  modeBadgeText: { color: COLORS.orange, fontSize: 12, fontWeight: "900" },
  actionRow: { flexDirection: "row", gap: 9, marginTop: 13 },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#60708A",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0A1829"
  },
  secondaryText: { color: COLORS.text, fontSize: 14, fontWeight: "800" },
  primaryButton: {
    flex: 1.25,
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: COLORS.orange,
    alignItems: "center",
    justifyContent: "center"
  },
  primaryDisabled: { backgroundColor: "#39485B" },
  primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" },
  pressed: { opacity: 0.76, transform: [{ scale: 0.98 }] }
});
