import { StyleSheet } from "react-native";

export const C = {
  bg: "#020A14",
  panel: "rgba(3,13,27,0.86)",
  card: "#071426",
  border: "#33445C",
  text: "#F5F7FB",
  muted: "#AEB7C8",
  orange: "#FF6800",
  purple: "#8B4DFF",
  cyan: "#22D3EE",
  cyanSoft: "rgba(34,211,238,0.14)",
  blue: "#7288AA",
  green: "#23C96B"
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  backgroundImage: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
  backgroundOverlay: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "rgba(2,10,20,0.62)" },
  sonarOverlay: { backgroundColor: "rgba(1,7,15,0.18)" },
  sonarBackground: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "#020812", overflow: "hidden" },
  sonarTopGlow: { position: "absolute", top: -120, alignSelf: "center", width: 210, height: 360, borderRadius: 105, backgroundColor: "rgba(34,211,238,0.28)", opacity: 0.8 },
  sonarRadarRing: { position: "absolute", alignSelf: "center", top: 54, borderWidth: 1, borderColor: "rgba(34,211,238,0.18)", borderRadius: 999 },
  sonarRadarRingOuter: { width: 430, height: 430 },
  sonarRadarRingMiddle: { width: 310, height: 310, top: 114, opacity: 0.7 },
  sonarRadarRingInner: { width: 190, height: 190, top: 174, opacity: 0.65 },
  sonarSweep: { position: "absolute", top: 60, alignSelf: "center", width: 2, height: 620, backgroundColor: "rgba(34,211,238,0.38)", transform: [{ rotate: "-13deg" }] },
  sonarHorizon: { position: "absolute", left: -40, right: -40, bottom: 210, height: 1, backgroundColor: "rgba(34,211,238,0.34)" },
  sonarTerrain: { position: "absolute", left: -80, right: -80, bottom: 78, height: 250, borderTopWidth: 1, borderColor: "rgba(34,211,238,0.24)", backgroundColor: "rgba(4,30,44,0.16)", transform: [{ skewY: "-10deg" }] },
  sonarTerrainLine: { position: "absolute", left: 0, right: 0, height: 1, backgroundColor: "rgba(34,211,238,0.16)" },
  sonarTerrainLineOne: { top: 46 },
  sonarTerrainLineTwo: { top: 100 },
  sonarTerrainLineThree: { top: 156 },
  sonarBottomShade: { position: "absolute", left: 0, right: 0, bottom: 0, height: 190, backgroundColor: "rgba(0,4,10,0.82)" },
  scroll: { flexGrow: 1, alignItems: "center" },
  frame: { width: "100%", maxWidth: 540, minHeight: "100%" },
  panel: { marginHorizontal: 4, paddingHorizontal: 30, paddingTop: 18, paddingBottom: 70, borderWidth: 1, borderColor: "rgba(65,83,111,0.48)", borderRadius: 10, backgroundColor: C.panel },
  sectionTitle: { color: C.orange, fontSize: 18, lineHeight: 23, fontWeight: "800", marginBottom: 9 },
  variant: { minHeight: 56, borderRadius: 14, borderWidth: 1, borderColor: C.border, backgroundColor: "rgba(5,15,29,0.92)", marginBottom: 10, paddingHorizontal: 12, paddingVertical: 5, flexDirection: "row", alignItems: "center", position: "relative", overflow: "visible" },
  selected: { borderColor: C.orange, borderWidth: 1.7 },
  fogSelected: { borderColor: "#B8C2CF", backgroundColor: "rgba(21,29,40,0.97)", shadowColor: "#B8C2CF", shadowOpacity: 0.28, shadowRadius: 14, shadowOffset: { width: 0, height: 0 }, elevation: 7 },
  sonarSelected: { borderColor: C.cyan, backgroundColor: "rgba(4,24,34,0.96)", shadowColor: C.cyan, shadowOpacity: 0.52, shadowRadius: 18, shadowOffset: { width: 0, height: 0 }, elevation: 10 },
  fogCardGlow: { position: "absolute", left: 7, right: 7, top: 7, bottom: 7, borderRadius: 11, borderWidth: 1, borderColor: "rgba(205,214,226,0.16)", backgroundColor: "rgba(205,214,226,0.025)" },
  sonarCardGlow: { position: "absolute", left: 7, right: 7, top: 7, bottom: 7, borderRadius: 11, borderWidth: 1, borderColor: "rgba(34,211,238,0.22)", backgroundColor: "rgba(34,211,238,0.035)" },
  pressed: { opacity: 0.78 },
  visual: { width: 72, alignItems: "center", justifyContent: "center", marginRight: 10 },
  visualSonarActive: { width: 72 },
  graphic: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  fogGraphic: { backgroundColor: "#303846", borderWidth: 1, borderColor: "rgba(205,214,226,0.32)", shadowColor: "#AEB7C8", shadowOpacity: 0.32, shadowRadius: 11 },
  fogGraphicActive: { width: 48, height: 48, borderRadius: 24, borderWidth: 1.5, borderColor: "rgba(220,227,236,0.68)", shadowOpacity: 0.55, shadowRadius: 16, elevation: 8 },
  graphicRing: { position: "absolute", borderWidth: 1, borderRadius: 50, borderColor: "rgba(224,231,239,0.3)" },
  graphicRingOuter: { width: 36, height: 36 },
  graphicRingMiddle: { width: 24, height: 24 },
  graphicRingInner: { width: 14, height: 14 },
  graphicLineHorizontal: { position: "absolute", width: 32, height: 1, backgroundColor: "rgba(224,231,239,0.24)" },
  graphicLineVertical: { position: "absolute", width: 1, height: 32, backgroundColor: "rgba(224,231,239,0.24)" },
  graphicDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: C.orange, borderWidth: 2, borderColor: "#FFFFFF", zIndex: 3 },
  fogHalo: { position: "absolute", width: 30, height: 30, borderRadius: 15, backgroundColor: "rgba(168,178,190,0.16)" },
  fogHaloActive: { width: 38, height: 38, borderRadius: 19, backgroundColor: "rgba(205,214,226,0.22)" },
  fogMistBandOne: { position: "absolute", width: 38, height: 8, borderRadius: 5, top: 12, backgroundColor: "rgba(225,231,238,0.09)", transform: [{ rotate: "-8deg" }] },
  fogMistBandTwo: { position: "absolute", width: 34, height: 7, borderRadius: 5, bottom: 12, backgroundColor: "rgba(225,231,238,0.07)", transform: [{ rotate: "7deg" }] },
  sonarGraphic: { width: 46, height: 46, borderRadius: 23, backgroundColor: "#04131C", borderWidth: 1.5, borderColor: "rgba(34,211,238,0.48)" },
  sonarGraphicActive: { width: 52, height: 52, borderRadius: 26, borderWidth: 2, borderColor: C.cyan, shadowColor: C.cyan, shadowOpacity: 0.75, shadowRadius: 16, shadowOffset: { width: 0, height: 0 }, elevation: 9 },
  sonarRingOuter: { width: 38, height: 38, borderColor: "rgba(34,211,238,0.32)" },
  sonarRingMiddle: { width: 26, height: 26, borderColor: "rgba(34,211,238,0.38)" },
  sonarRingInner: { width: 14, height: 14, borderColor: "rgba(34,211,238,0.44)" },
  sonarAxisHorizontal: { position: "absolute", width: 40, height: 1, backgroundColor: "rgba(34,211,238,0.18)" },
  sonarAxisVertical: { position: "absolute", width: 1, height: 40, backgroundColor: "rgba(34,211,238,0.18)" },
  sonarPulse: { position: "absolute", width: 38, height: 38, borderRadius: 19, borderWidth: 2, borderColor: "rgba(34,211,238,0.72)" },
  sonarSweep: { position: "absolute", width: 46, height: 46, alignItems: "center", justifyContent: "flex-start" },
  sonarBeam: { width: 2, height: 22, marginTop: 2, backgroundColor: C.cyan },
  sonarBlip: { position: "absolute", width: 6, height: 6, borderRadius: 3, top: 11, right: 10, backgroundColor: C.cyan, shadowColor: C.cyan, shadowOpacity: 0.9, shadowRadius: 8, elevation: 7 },
  sonarCoreOuter: { width: 14, height: 14, borderRadius: 7, backgroundColor: "#E8FDFF", alignItems: "center", justifyContent: "center", zIndex: 3 },
  sonarCoreInner: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.cyan },
  variantCopy: { flex: 1, minWidth: 0, paddingRight: 34 },
  variantTitle: { color: C.text, fontSize: 18, lineHeight: 21, fontWeight: "800", marginBottom: 1 },
  fogText: { color: "#E3E8EF", textShadowColor: "rgba(205,214,226,0.28)", textShadowRadius: 6 },
  sonarText: { color: C.cyan, textShadowColor: "rgba(34,211,238,0.45)", textShadowRadius: 8 },
  variantDescription: { color: C.muted, fontSize: 13, lineHeight: 17 },
  variantMark: { position: "absolute", top: 8, right: 9 },
  mark: { width: 30, height: 30, borderRadius: 15, borderWidth: 1.5, borderColor: "#6E819F", alignItems: "center", justifyContent: "center", alignSelf: "flex-start" },
  markSmall: { width: 25, height: 25, borderRadius: 13 },
  markOn: { backgroundColor: C.orange, borderColor: C.orange },
  markOnSonar: { backgroundColor: C.cyan, borderColor: C.cyan, shadowColor: C.cyan, shadowOpacity: 0.65, shadowRadius: 8 },
  check: { color: "#111315", fontSize: 18, fontWeight: "900" },
  checkSonar: { color: "#02202A" },
  selectedModeSummary: { minHeight: 44, borderRadius: 11, borderWidth: 1, borderColor: C.border, backgroundColor: C.card, paddingHorizontal: 12, marginBottom: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  selectedModeText: { color: C.text, fontSize: 15, lineHeight: 20, fontWeight: "800" },
  selectedModeChange: { color: C.orange, fontSize: 14, lineHeight: 19, fontWeight: "800" },
  subhead: { color: C.text, fontSize: 18, lineHeight: 23, fontWeight: "800", marginTop: 6, marginBottom: 8 },
  row: { flexDirection: "row", gap: 10, marginBottom: 14 },
  player: { flex: 1, minHeight: 86, borderRadius: 18, borderWidth: 1.3, borderColor: "rgba(114,136,170,0.72)", backgroundColor: "rgba(7,20,38,0.96)", paddingHorizontal: 13, paddingTop: 13, paddingBottom: 11, justifyContent: "space-between", position: "relative", shadowColor: "#000000", shadowOpacity: 0.28, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 7 },
  playerIcon: { fontSize: 24, lineHeight: 27, marginBottom: 8, fontWeight: "900" },
  playerText: { color: C.text, fontSize: 17, lineHeight: 21, fontWeight: "900", letterSpacing: -0.2 },
  playerMark: { position: "absolute", top: 10, right: 10 },
  inlineContactButton: { flex: 1, minHeight: 58, borderRadius: 11, borderWidth: 1, borderColor: C.orange, backgroundColor: C.card, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", justifyContent: "center" },
  inlineContactIcon: { color: C.orange, fontSize: 24, lineHeight: 26, marginRight: 6, fontWeight: "800" },
  inlineContactText: { flexShrink: 1, color: C.text, fontSize: 15, lineHeight: 20, fontWeight: "800", textAlign: "center" },
  difficulty: { flex: 1, minHeight: 68, borderRadius: 11, borderWidth: 1, borderColor: C.border, backgroundColor: C.card, paddingHorizontal: 10, paddingVertical: 6 },
  diffTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", minHeight: 18 },
  stars: { fontSize: 19, letterSpacing: 0.5 },
  diffTitle: { color: C.text, fontSize: 15, lineHeight: 20, fontWeight: "700" },
  diffSubtitle: { color: C.muted, fontSize: 13, lineHeight: 18 },
  difficultyInfo: { borderWidth: 1, borderColor: "rgba(255,104,0,0.58)", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, marginTop: 0, marginBottom: 14, backgroundColor: "rgba(17,29,45,0.92)" },
  difficultyInfoTitle: { color: C.text, fontSize: 17, lineHeight: 22, fontWeight: "900", marginBottom: 3 },
  difficultyInfoText: { color: C.muted, fontSize: 15, lineHeight: 21, marginBottom: 8 },
  infoRow: { minHeight: 28, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  infoLabel: { color: C.muted, fontSize: 14, lineHeight: 19, fontWeight: "700" },
  infoValue: { flexShrink: 1, color: C.text, fontSize: 14, lineHeight: 19, fontWeight: "800", textAlign: "right" },
  inviteSummary: { borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 10, marginBottom: 10, backgroundColor: C.card },
  inviteSummaryTitle: { color: C.text, fontSize: 14, fontWeight: "700", marginBottom: 8 },
  friendChip: { minHeight: 44, borderRadius: 10, backgroundColor: "rgba(20,39,61,0.95)", paddingHorizontal: 12, marginBottom: 6, flexDirection: "row", alignItems: "center" },
  friendChipText: { flex: 1, color: C.text, fontSize: 14 },
  friendRemove: { color: C.orange, fontSize: 26, lineHeight: 30, paddingHorizontal: 6 },
  button: { minHeight: 56, borderRadius: 12, backgroundColor: C.orange, alignItems: "center", justifyContent: "center", marginTop: 10, elevation: 6 },
  buttonPressed: { opacity: 0.82 },
  buttonText: { color: "#111315", fontSize: 23, lineHeight: 28, fontWeight: "900" },
  modalSafe: { flex: 1, backgroundColor: C.bg },
  modalHeader: { minHeight: 76, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: C.border },
  modalTitle: { color: C.text, fontSize: 24, fontWeight: "900" },
  modalSubtitle: { color: C.muted, fontSize: 13, marginTop: 2 },
  doneButton: { minWidth: 64, minHeight: 44, borderRadius: 12, backgroundColor: C.orange, alignItems: "center", justifyContent: "center", paddingHorizontal: 14 },
  doneButtonText: { color: "#111315", fontSize: 15, fontWeight: "900" },
  contactList: { padding: 14 },
  contactRow: { minHeight: 66, borderRadius: 12, borderWidth: 1, borderColor: C.border, paddingHorizontal: 12, marginBottom: 8, flexDirection: "row", alignItems: "center", backgroundColor: C.card },
  contactRowSelected: { borderColor: C.orange, backgroundColor: "rgba(80,38,8,0.42)" },
  contactAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#17304E", alignItems: "center", justifyContent: "center", marginRight: 12 },
  contactAvatarText: { color: C.text, fontSize: 17, fontWeight: "900" },
  contactCopy: { flex: 1, minWidth: 0 },
  contactName: { color: C.text, fontSize: 16, fontWeight: "800" },
  contactPhone: { color: C.muted, fontSize: 13, marginTop: 2 },
  emptyText: { color: C.muted, fontSize: 15, textAlign: "center", marginTop: 40 }
});
